### ISSUE TITLE
MongoDB's Server Discovery and Monitoring engine is deprecated

### ISSUE THREAD

**Issue by GeovaneBaldan** [GeovaneBaldan/weekend-project-backend#8]
Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version.
We need to use the new version of this engines, so pass option { useUnifiedTopology: true } to the MongoClient constructor.

**Comment by GabrielVander** [comment]
It was supposedly fixed on version loopback-connector-mongodb v4.2.0 

https://github.com/strongloop/loopback-connector-mongodb/issues/540

**Comment by GeovaneBaldan** [comment]
nice
